cabinet/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

    root 'welcome#index'
end

cabinet/app/models/doc.rb
class Doc < ActiveRecord::Base
  belongs_to :user

end

cabinet/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :docs
end

cabinet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cabinet/app/controllers/docs_controller.rb
class DocsController < ApplicationController

  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs= Doc.where(user_id: current_user)
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def new
    @doc = current_user.docs.build
  end


  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end

  end

  def edit
  end

  def show
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def doc_params
    params.require(:doc).permit(:title, :content)
  end

  def find_doc
     @doc=Doc.find(params[:id])
  end
end

cabinet/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_now

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

cabinet/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

cabinet/app/helpers/application_helper.rb
module ApplicationHelper
end

cabinet/app/helpers/docs_helper.rb
module DocsHelper
end

cabinet/app/helpers/users_helper.rb
module UsersHelper
end

cabinet/app/helpers/welcome_helper.rb
module WelcomeHelper
end

cabinet/app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

cabinet/app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Edit !!

  = render 'form'

=link_to "Cancel", doc_path(@doc)

cabinet/app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href:(url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)

    - else
      %h2 Creat Doc!
      %p Start Creating Documents and Organizing your Life!
      %button= link_to "Creat Doc", new_doc_path

cabinet/app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc


  =render 'form'

cabinet/app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)

    .buttons
      =link_to "Fix Doc", edit_doc_path, class: "button"
      =link_to "Trash It", doc_path(@doc), method: :delete, data: {confirm:"Are you Sure?"}, class: "button"

cabinet/app/views/layouts/application.html.haml
!!!
%html
%header
  %title Cloud Cabinet | Your Web-Based Notebook
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %header
    .header_inner
      = link_to "CloudCabinet", root_path, id:"logo"

      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete

        - else
          = link_to "Log In", new_user_session_path

    %p.notice= notice
    %p.alert= alert

  = yield

cabinet/app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 CloudCabinet
    %p Your Web Based Notebook. Organized Always
    %button= link_to "Sign Up", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Franzen fingerstache four loko freegan pork belly mumblecore bushwick




#bottom_cta
  .wrapper
    %h2 Go Ahead
    %%br
    %button= link_to "Join Now", new_user_registration_path